name: Build and Release Android APK

on:
    push:
        branches: ["main"]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3
              with:
                  api-level: 34
                  build-tools: 34.0.0

            - name: Install jq
              run: sudo apt-get update && sudo apt-get install -y jq

            - name: Install Gradle 8.8
              run: |
                  curl -sLO https://services.gradle.org/distributions/gradle-8.8-bin.zip
                  unzip -q gradle-8.8-bin.zip -d $HOME/gradle
                  echo "$HOME/gradle/gradle-8.8/bin" >> $GITHUB_PATH
                  gradle --version

            - name: Download latest yt-dlp wheel
              run: |
                  mkdir -p app/src/main/python
                  WHEEL_URL=$(curl -s https://pypi.org/pypi/yt-dlp/json | jq -r '.urls[] | select(.filename | endswith(".whl")) | .url' | head -n 1)
                  FILENAME=$(basename "$WHEEL_URL")
                  wget -O "app/src/main/python/$FILENAME" "$WHEEL_URL"
                  echo "$FILENAME" > app/src/main/python/yt_dlp_filename.txt

            - name: Build Debug APK
              run: |
                  export PATH=$HOME/gradle/gradle-8.8/bin:$PATH
                  gradle assembleDebug --no-daemon

            - name: Create and push tag
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  TAG="v${{ github.run_number }}"
                  git tag $TAG
                  git push origin $TAG

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ github.run_number }}
                  name: Release ${{ github.run_number }}
                  draft: false
                  prerelease: false
                  files: app/build/outputs/apk/debug/app-debug.apk
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
